### PR TITLE
Added droplet code dropletanal, dropletfind

### PR DESCRIPTION
**Pull request by ordirules**
Added droplet code to find droplets on a detector.
Todo: Need a good photonizing algorithm.

Questions:
- What should I write as header? (copyright etc)
- Is the way I include the c files okay? (they're in src but they need to be referenced to cython properly)
- i have a notebook ready to run a demonstration, where should i put it?
- currently the c wrapper is a cython code. we could make a wrapper accessing this wrapper and put this in speckle.py as Sameera suggested to me?

@sameera2004 @ericdill @tacaswell @danielballan @pavoljuhas

### CODE REVIEW

**Comment by sameera2004** [comment]
Thanks @ordirules  the notebook you can add to the https://github.com/scikit-beam/scikit-beam-examples

**Comment by sameera2004** [comment]
@ordirules  We have to modify the `skbeam`, `setup.py` file.

 Header is following, please get it from one of our other modules. Inside that please include about the original owners and you are modifying it etc.. 
`
# ######################################################################
# Copyright (c) 2014, Brookhaven Science Associates, Brookhaven        #
# National Laboratory. All rights reserved.                            #
#                                                                      #
# Redistribution and use in source and binary forms, with or without   #
# modification, are permitted provided that the following conditions   #
# are met:                                                             #
#                                                                      #
# * Redistributions of source code must retain the above copyright     #
#   notice, this list of conditions and the following disclaimer.      #
#                                                                      #
# * Redistributions in binary form must reproduce the above copyright  #
#   notice this list of conditions and the following disclaimer in     #
#   the documentation and/or other materials provided with the         #
#   distribution.                                                      #
#                                                                      #
# * Neither the name of the Brookhaven Science Associates, Brookhaven  #
#   National Laboratory nor the names of its contributors may be used  #
#   to endorse or promote products derived from this software without  #
#   specific prior written permission.                                 #
#                                                                      #
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS  #
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT    #
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS    #
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE       #
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,           #
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES   #
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR   #
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)   #
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,  #
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OTHERWISE) ARISING   #
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE   #
# POSSIBILITY OF SUCH DAMAGE.                                          #
########################################################################
`

**Comment by ordirules** [comment]
why does setup.py need to be modified? cython looks for all files and as far as i can tell cython takes care of compiling the c code. I'm very new at this though, so I could be wrong. It was compiled just fine for me as is ``` python source develop```

**Comment by sameera2004** [comment]
You will need it when you have python wrapper

**Comment by sameera2004** [comment]
@ordirules I am adding @vivekthampy to these discussions because he is going to use/test this code

**Comment by stuwilkins** [comment]
@ordirules @sameera2004 Hi, I was just looking at this thread.... I have been looking at this find algorithm for a while. A version is in csxtools which is for our FastCCD to do single photon counting (written by from scratch by me). It is a bit stupid or brute force for my liking, but it works. It is also multithreaded using OpenMP in a scatter gather mode.

Given we are on site, perhaps we could discuss these over coffee and see if we can come up with one general solution? What do you think.

I doubt that @vivekthampy has time at the moment to test any of this, but @cmazzoli or @ambarb from CSX may also be interested?

**Comment by sameera2004** [comment]
@stuwilkins I haven't tested this code yet. Yes I would like to discuss.

**Comment by ordirules** [comment]
Thanks, I looked for @vivekthampy but could not find him before. 

As context, the code I have added was code written by Larry Lurio and Mark Sutton. It was used as a plugin in yorick and I had used it before in the past. @sameera2004 asked me to show them the code so I felt it would be fitting to have it ported to python rather than trying to learn yorick.

I'd be happy to join you guys to discuss, it will be interesting.

**Comment by ordirules** [comment]
example in https://github.com/scikit-beam/scikit-beam-examples/pull/59
(for discussion purposes)

**Comment by licode** [comment]
@ordirules , thanks for adding droplet code and examples. It will be helpful if more unit tests can be added.

**Comment by cmazzoli** [comment]
I am surely interested to participate, if possible
Thanks!

**Comment by ordirules** [comment]
@Lili good idea, unit tests should be added. We can do so after the discussion, as likely things will change. We will meet this friday or monday.

**Comment by ordirules** [comment]
@ericdill Travis failed and it's a histogram assertion error (nothing to do with droplet code here).  The mismatch is  1.1111111111111143%, that's a 3rd sig fig, a little close. We'll need to resolve this.
I can try to take a look later as well.

**Comment by ericdill** [comment]
That is an intermittent failure.

**Comment by stuwilkins** [comment]
Why is this intermittent? Surely the results are not intermittent. Is this a rounding issue?

On Mar 6, 2016, at 9:07 PM, Eric Dill <notifications@github.com<mailto:notifications@github.com>> wrote:


That is an intermittent failure.

**Comment by ericdill** [comment]
It only failed on Python 3.4 and if I restart Travis it will pass

**Comment by ericdill** [comment]
I have seen this a number of times but have not had a chance to investigate

**Comment by sameera2004** [comment]
I have noticed this too!

**Comment by ordirules** [comment]
I don't know if that's acceptable that our test code disrupts others PR's. I'm sure we can fix this :-). @pavoljuhas , @chrisvam @ericdill and I wrote this code together, maybe someone else has an idea?
I'll try to look into this tonight. 1% is also not a small error in my opinion

@ericdill do you know if it always fails on python 3.4?

**Comment by stuwilkins** [comment]
Has anyone run a loop on one of our systems just doing the tests over and over recording how many test failures there are? That would show if it was a problem or a travis issue.

**Comment by sameera2004** [comment]
@ordirules It is not happening always only sometimes

**Comment by ericdill** [comment]
@ordirules What is the plan here?  I was not around for the in-person discussion.  Do you have a sense of if we going to pursue this or use skimage?

**Comment by ordirules** [comment]
Hi all,

   Sorry for the late reply. Very busy. This should probably be closed soon. There was a meeting with @stuwilkins, @sameera2004, @vivekthampy, @tacaswell and others a while back and @tacaswell suggested to check other libraries. To sort of summarize from memory, there were two main points of discussion:
1. This current code could likely be replaced by existing code (in scipy or scikit-image)
2. There are different droplet algorithms that each have their own advantage depending on the specific purpose. I won't get into details but this code was geared for higher energy photons. There is another version of droplet analysis that seems to work much better for lower energy photons (where the number of counts per droplet is similar to the background noise).

I will address point 1 here. The second is out of scope of the PR but may deserve attention in the future by those who use any of these algorithms routinely. (Unfortunately, I haven't had the need for droplet analysis for a while)

The results so far:
I did some timing comparisons and it seems that scipy is faster, with the exception of one piece, finding the center of mass. I have a feeling we could still find faster code (I'll search later, busy...)

Here is the idea. Let's assume an image (`img`) and a mask image (which I call `bimg`).
Here is the droplet code call:
```python
    from skbeam.core.accumulators.droplet import dropletfind, dropletanal

    npeaks, limg = dropletfind(bimg)
    npix, xcen, ycen, adus, idlist = dropletanal(img, dimg, npeaks)
```
and a scipy alternative:
```python
    import scipy.ndimage.measurements as smt

    limg, numlabels = smt.label(bimg)
    coms = np.array(smt.center_of_mass(img,labels=limg,index=np.arange(2,numlabels)))
    ADUS = smt.sum(img, labels=limg, index=np.arange(2,numlabels))
```
I ran each 100 times and timed each run. I timed each separate call: the labeling, finding the centers of mass, and integrating the ADUS.

timing results

All in all, I don't think this code would be useful. Will get back to finding the last piece later.... This PR should be resolved soon (and cancelled).

**Comment by ordirules** [comment]
I have looked at the scikit image libraries as well as scipy. Here's a summary
(@tacaswell if you had time to take a look and knew of a better alternative for these functions let me know)

Droplet:
```python
    from skbeam.core.accumulators.droplet import dropletfind, dropletanal

    npeaks, limg = dropletfind(bimg)
    npix, xcen, ycen, adus, idlist = dropletanal(img, dimg, npeaks)
```
Scipy:
```python
    import scipy.ndimage.measurements as smt

    limg, numlabels = smt.label(bimg)
    coms = np.array(smt.center_of_mass(img,labels=limg,index=np.arange(2,numlabels)))
    ADUS = smt.sum(img, labels=limg, index=np.arange(2,numlabels))
```
Skimage:
```python
import skimage.measure as skmsr
limg_skimage, numlabels_skimage = skmsr.label(bimg,return_num=True,connectivity=1,background=0)
props_skimage = skmsr.regionprops(limg_skimage+1,img)
```
Timing is last figure here:
https://github.com/ordirules/notebooks/blob/master/droplet.ipynb

Overall, the droplet algorithm seems to be fastest in this case but there are a few things to note:
1. This is a sparse array of connected regions. Dropletanal seems to do best when handed sparse regions, compared to scikit image and scipy. However, I have given it more populated regions and it is slightly slower than scipy for the labeling sometimes, but not much slower (and overall always faster). This would need to be more thoroughly investigated
2. scikit image's function to return statistics of the droplets returns a whole bunch of other junk. Maybe if there was a way to select the desired properties (centroids and sum of droplet) it would be faster?
3. For scipy, I need to make two function calls to obtain centroids and counts per droplet, resulting in two passes in the data array. Perhaps scipy could be improve to return both in one pass.

From this, there are I think two options:
1. Incorporate the droplet algorithm into scikit-beam.
2. Find the pieces that make the droplet algorithm fast and try to incorportate them into scikit-image or scipy (or both).

I'm a proponent of number 2 and am willing to dig in those libs.
What do you think? We could analyze this more thoroughly once we choose an option.
@tacaswell , @danielballan , this should close this discussion :-)

**Comment by chrisvam** [comment]
Hi Julien,

Thanks for looking at this droplet stuff.  After I finish with the angular integration PR and a histogram-tweak PR I’m hoping to work on droplet algorithms as well, since it’s used a lot at LCLS.  We have several algorithms (currently python calling C++ via boost).  The two most important features that we use are:

- having a higher threshold to start a droplet, and a second lower threshold to “join” a droplet.  I believe this gives the best photon energy/position resolution (when analyzing images with single photons).  It’s an old idea we used for years in high-energy physics
- for many of our experiments there are physics backgrounds that vary across the image (e.g. a “water ring”) that means the noise varies across the image.  So we have algorithms that evaluate the “local” noise around a droplet and require that the droplet be statistically significant above the local noise.

Just so you know.  I hope to help with this when I’m able...

chris

On Aug 12, 2016, at 8:23 PM, Julien Lhermitte <notifications@github.com<mailto:notifications@github.com>> wrote:


I have looked at the scikit image libraries as well as scipy. Here's a summary
(@tacaswell<https://github.com/tacaswell> if you had time to take a look and knew of a better alternative for these functions let me know)

Droplet:

    from skbeam.core.accumulators.droplet import dropletfind, dropletanal

    npeaks, limg = dropletfind(bimg)
    npix, xcen, ycen, adus, idlist = dropletanal(img, dimg, npeaks)

Scipy:

    import scipy.ndimage.measurements as smt

    limg, numlabels = smt.label(bimg)
    coms = np.array(smt.center_of_mass(img,labels=limg,index=np.arange(2,numlabels)))
    ADUS = smt.sum(img, labels=limg, index=np.arange(2,numlabels))

Skimage:

import skimage.measure as skmsr
limg_skimage, numlabels_skimage = skmsr.label(bimg,return_num=True,connectivity=1,background=0)
props_skimage = skmsr.regionprops(limg_skimage+1,img)

Timing is last figure here:
https://github.com/ordirules/notebooks/blob/master/droplet.ipynb

Overall, the droplet algorithm seems to be fastest in this case but there are a few things to note:
1. This is a sparse array of connected regions. Dropletanal seems to do best when handed sparse regions, compared to scikit image and scipy. However, I have given it more populated regions and it is slightly slower than scipy for the labeling sometimes, but not much slower (and overall always faster). This would need to be more thoroughly investigated
2. scikit image's function to return statistics of the droplets returns a whole bunch of other junk. Maybe if there was a way to select the desired properties (centroids and sum of droplet) it would be faster?
3. For scipy, I need to make two function calls to obtain centroids and counts per droplet, resulting in two passes in the data array. Perhaps scipy could be improve to return both in one pass.

From this, there are I think two options:
1. Incorporate the droplet algorithm into scikit-beam.
2. Find the pieces that make the droplet algorithm fast and try to incorportate them into scikit-image or scipy (or both).

I'm a proponent of number 2 and am willing to dig in those libs.
What do you think? We could analyze this more thoroughly once we choose an option.
@tacaswell<https://github.com/tacaswell> , @danielballan<https://github.com/danielballan> , this should close this discussion :-)

**Comment by ordirules** [comment]
Thanks for the feedback @chrisvam. I don't work on anything related to droplets right now (but I have used it for star finding and peak finding) so I wouldn't be the right person to keep pushing this. But I would be interested to be included in the discussion.

Any plans to use cython since we started with histogram?

Anyway, sounds like there are two parallel possibilities: 
1. Speeding up the scipy or scikit image droplet algorithm by some means, if it can be. (Optimized code or have options allow the calculations of subsets of what it's currently doing) I will play with that in my free time (unless someone else wants to try). I do use that algorithm for other reasons (astronomy hobby and sometimes research for crude peak finding), so I'd be happy to see it as efficient as possible.
2. Decide whether the beamline community would benefit from a specialized droplet algorithm. It sounds like yes from your two points but probably requires some kind of discussion with key members of the broader community. Sounds like you guys are working with this.

Good luck with the other PRs!

**Comment by danielballan** [comment]
Let's get a sample data set to profile together (such that a couple of us can work on this at the same time and share results). I'd like to see how trackpy's perforamance compares to scikit-image and to this.

**Comment by marcocamma** [comment]
Hi,

I am currently working on a dataset where I need to dropletize the images. The detector noise is ~ 5 ADU. And one photon is ~ 120 ADU. I can provide some data if it can be of any use. I have been using scipy and skimage up to now and I will probably test skbeam method once I figere out how to download a PR ;)

**Comment by danielballan** [comment]
@marcocamma You want:

```
git remote add ordirules git@github.com: ordirules/scikit-beam  # if you use SSH credentials for git
git remote add ordirules https://github.com/ordirules/scikit-beam  # if you don't
git remote update
git checkout ordirules/droplet
```

We are in the process of evaluating how this compares to scipy, skimage, and trackpy. Very interested in what you learn.

**Comment by ordirules** [comment]
@marcocamma yes it would be great if you could test your data on the code.

@danielballan  this is the best data I could find, I pushed it here (I know this isn't the best way, but I think for this small file should be okay):
https://github.com/ordirules/notebooks/blob/master/data/0776-droplettestimg.hd5

The elements in this hdf5 file are listed here:
https://github.com/ordirules/notebooks/blob/master/droplet-sampleimg.ipynb
There is a low and high region. It would be good to  test the code in these two regions (although only the latter is of interest)
This might not be the best data. This was the fast CCD by the Berkeley group we tried,  60Hz frame rate on some old data. The count rates were still high enough that you can see speckle near low q (and we found we didn't need to droplet algorithm for good results).

@marcocamma it sounds like you are testing a real scenario, and yes very interested to see what you learn. I don't use droplet code anymore because the detector I use is a counting detector.

@stuwilkins may also be interested in following. His case is different. Their droplets are barely above the noise so the initial binarizing image step doesn't work for them.

**Comment by marcocamma** [comment]
@danielballan thanks for the instructions !
I am about to try them out (altough it is getting late here in europe)
I have tested scipy, skimage and trackpy.
So far (for my data): trackpy did not work very well. skimage gave same results as scipy but was ~3 times slower. I will test the skbeam version and report back.
How should I do it ? probably best is to write a short report or a jupyter notebook but I don't know where I can upload it. i appreciate any suggestion !
more later

**Comment by marcocamma** [comment]
for those who want to play with the data youself:

it is an almost isotropic radiation but you will see lots of temporary shielding.

100 images per file (100MB each). to load them
imgs = np.load(fname)

https://cloud.ipr.univ-rennes1.fr/index.php/s/kCdFoXwXxxShlyk (with beam)
https://cloud.ipr.univ-rennes1.fr/index.php/s/Ms6haQM9gUXzTaa [darks, probably not that useful]

**Comment by marcocamma** [comment]
Hi again,

so I found some time to work on the comparison of the different methods (see picture below and code here: https://gist.github.com/marcocamma/b6cdb6f6eb42f4f31040e3203fc77584).

The results of scipy,skimage and skbeam are very similar. In terms of speed skbeam is much faster than others.

By playing with the code I found out a problem in dropletanal. You should be able to reproduce it by running the code (only tested with python 3.5.2):
```python
   from skbeam.core.accumulators.droplet import dropletfind, dropletanal
   img=np.random.random_integers(0,255,size=(700,700))
   n,a=dropletfind(img)

   # this works
   npix, xcen, ycen, adus, idlist=dropletanal(img,a,n)

   # calling it a second time will crash the session
   npix, xcen, ycen, adus, idlist=dropletanal(img,a,n)
```

Let me know if I can be of any further help.
marco
image

**Comment by ordirules** [comment]
@marcocamma this is great! Thanks, it's also interesting to see how fast this code is!
Thanks for catching the bug, it's a seg fault (because `a` is modified after every call), the proof of that is switching to this fixes it:
```python
npix, xcen, ycen, adus, idlist=dropletanal(img,np.copy(a),n)
```
(I'll make the change later, thanks again)

I discussed with @chrisvam, as well as @danielballan and @tacaswell. @chrisvam has a nicer version of the droplet algorithm, with more features, developed at the LCLS (see his earlier comment above). When he has time, he will make a PR. So for now, in my opinion I think we should leave this PR to keep some open discussion on the algorithm.

In the mean time, I am sure the skbeam community would definitely appreciate your continued input and help.

**Comment by ordirules** [comment]
PS: It could be a good idea to try to have skbeam, scipy and scikit-image all agree on the final results, for a fairer timing (but likely this won't change). Unfortunately, this current droplet algorithm isn't as flexible as scikit-image or scipy.

These parameters all yielded the same results for me (`bimg` is an integer binary image):
```python
# the droplet analysis

numlabels_drop, limg_drop = dropletfind(bimg)
npix_drop, xcen_drop, ycen_drop, adus_drop, idlist_drop = dropletanal(img, limg_drop, numlabels_drop)

#scipy
limg_scipy, numlabels_scipy = smt.label(bimg)
coms_scipy = np.array(smt.center_of_mass(img,labels=limg_scipy,index=np.arange(0,numlabels_scipy)))
adus_scipy = smt.sum(img, labels=limg_scipy, index=np.arange(0,numlabels_scipy))

#skimage
limg_skimage, numlabels_skimage = skmsr.label(bimg,return_num=True,connectivity=1,background=0)
props_skimage = skmsr.regionprops(limg_skimage+1,img)
```

**Comment by marcocamma** [comment]
@chrisvam could you please share your code ? I may be able to help out and test it. I will be at LCLS for a week starting on Oct 5th ... in case you want to discuss in person.

**Comment by chrisvam** [comment]
Hi Marco,

At the moment, the code is difficult to share because it is a boost-python wrapper around some C++.  It works easily in the LCLS psana-python environment:

https://confluence.slac.stanford.edu/display/PSDM/Hit+and+Peak+Finders

In a nutshell it has two-thresholds (a high threshold to start a peak, and a lower threshold to join a peak) and one can also cut on signal-over-local-noise.  Now that I've finished adding in some r-phi projection and histogramming code into scikit-beam, I would like to make the peak-finder my next project to get into scikit-beam, perhaps using cython instead of boost.  But it will likely be a while (have to work on cspad/epix detector corrections).  Our current interface needs improvement.

If it's useful for you I can point you to the C++ code (which we call from python) at LCLS.

**Comment by chrisvam** [comment]
Also, for Marco:  if you decide you want to try the LCLS peak-finders we have a new-ish graphical tool for tuning peak-finding parameters:

https://confluence.slac.stanford.edu/display/PSDM/Graphical+Image+Analysis#GraphicalImageAnalysis-PeakFinder

We can have a look at this together when you are at LCLS, if that would be useful.

**Comment by marcocamma** [comment]
sure. I might also help in porting your code into pure python/cython. if you can point me to your code I can start to have a look at it. 
soon Marco 

On September 30, 2016 10:40:54 PM GMT+02:00, chrisvam <notifications@github.com> wrote:
>Also, for Marco:  if you decide you want to try the LCLS peak-finders
>we have a new-ish graphical tool for tuning peak-finding parameters:
>
>https://confluence.slac.stanford.edu/display/PSDM/Graphical+Image+Analysis#GraphicalImageAnalysis-PeakFinder
>
>We can have a look at this together when you are at LCLS, if that would
>be useful.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scikit-beam/scikit-beam/pull/423#issuecomment-250847037

-- 
Envoyé depuis un appareil mobile. désolé pour la brièveté de mon message.

Sent from a mobile device. Please excuse my brevity.

**Comment by chrisvam** [comment]
Sounds great, Marco.  You can find the code here (in the LCLS filesystem):

/reg/g/psdm/sw/releases/ana-current/ImgAlgos/include/AlgImgProc.h

The routine is peakFinderV4.  My guess it will be quite a bit of work to get it into good enough shape to go into scikit-beam, but we can discuss next time you're in town.  Thanks...

**Comment by ordirules** [comment]
just curious, any progress with droplet code @marcocamma @chrisvam?
I'd be interested to see it :-)

**Comment by chrisvam** [comment]
Hi Julien,

I believe @msdubrovin was working on it as recently as last week, but some pressure to fix issues with some fiber diffraction analysis code have intervened.  Also, in general, we have some new pressure from LCLS management to work on the LCLS-II upgrade which will affect what we can work on (we go from 2GB/s to 200Gb/s in 3 years, which is daunting).

From my perspective, two-threshold peak-finding remains the highest-priority item we have for skbeam.

chris

**Comment by ordirules** [comment]
@chrisvam thanks for sharing. No worries, it's not urgent, but I'm interested to see how it goes.
Indeed, 100 fold improvement in bandwidth sounds pretty daunting. Good luck! :-)

**Comment by licode** [comment]
Back to this interesting algo, are we going to merge this soon? Or use the functions in scipy, skimage? Are the theories similar between algo in this PR and the one in skimage http://scikit-image.org/docs/dev/api/skimage.measure.html#label?

**Comment by ordirules** [comment]
I think the consensus is that this code should not be merged since @chrisvam is working on a solution. The PR is left open to provide discussion.
There was a short meeting a while ago about this with @sameera2004, @stuwilkins and others.

Scipy and scikit-image also both offer alternatives to this algorithm, as shown.

If anyone has other opinions, feel free to write (as well as if you think we should just close this and move discussion to somewhere more appropriate).

**Comment by ericdill** [comment]
@ordirules @danielballan @licode @chrisvam -- What's the status on this?

**Comment by licode** [comment]
I think this is to be closed.

**Comment by ordirules** [comment]
I agree. Closing. When @chrisvam is ready to discuss again we'd be interested to see input.
If anyone finds this code useful we can also re-evaluate whether to include or not. Right now, there is no current application.

**Comment by chrisvam** [comment]
Hi guys,

Sorry for the slow replies ... pressure from the upcoming 200GB/s at LCLS is somewhat intense.  One of use (mikhail dubrovin) has been doing some work on droplet analysis.  We hope to try to put that in scikit-beam at some point (we still strongly believe in the scikit-beam effort).

chris

**Pull request closed without merging**
