### PR TITLE
Finish up and supersede #434

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
why the close/reopen?  I thought travis was happy

**Comment by tacaswell** [comment]
I see this + a grayed out merge box:

```
This branch is out-of-date with the base branch
Merge the latest changes from master into this branch.
As an administrator, you may still merge this pull request.
```

Trying to restart to make github happy.

**Comment by ericdill** [comment]
Oh. I probably just need to rebase and push.  Also why is github suggesting that you should merge master into the feature branch?

**Comment by ericdill** [comment]
ok rebased, squashed the PEP8 commit and force pushed. Let's see if travis is still happy

**Comment by tacaswell** [comment]
There are some workflows where that makes sense (mostly if you plan to squash the PR into a single commit at the end _anyway_).  There is some flag someplace that will disable this bit of verification....

**Comment by tacaswell** [comment]
ok, I un-set the 'branch must be uptodate' flag in the protected branch menu.

**Comment by ericdill** [comment]
Ah neat, unchecking that button did in fact get rid of the 'merge master' button that was there

**Comment by ericdill** [comment]
@tacaswell this is ready to go

**Pull request merged**
