### PR TITLE
added bin_centers property

### PR DESCRIPTION
**Pull request by ordirules**
I could use this for binnedstat `bin_centers` property to `BinnedStatistic`.
@chrisvam @tacaswell @danielballan 

Saves typing time.
Would this be okay? Overhead should be slight since the calculation is solely in the initial declaration.

thanks!

### CODE REVIEW

**Comment by chrisvam** [comment]
For what it's worth:  it looks useful to me...

**Comment by ericdill** [comment]
LGTM

**Comment by danielballan** [comment]
👍

**Comment by ordirules** [comment]
:ok_hand:

**Pull request merged**
