### PR TITLE
MNT: Rename skxray -> skbeam

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
Looks like everything is passing. This should be good to go. Could someone have a look?

**Comment by tacaswell** [comment]
@ericdill this needs a rebase

**Comment by ericdill** [comment]
@tacaswell  Should I wait for other PRs to land? Or just rebase this, merge it and make the other PRs rebase on top of this?

**Comment by danielballan** [comment]
I like your idea of waiting for hackathon PRs to land.

**Comment by ericdill** [comment]
I'll get this fixed as the last thing before tagging v0.0.6

**Comment by ericdill** [comment]
Fingers crossed 06c9cc4 will pass travis and then I can cut the v0.0.6 release

**Comment by ericdill** [comment]
Alright, this is going to break ALL THE USER CODE! Here goes!

**Comment by danielballan** [comment]
:boom:

**Pull request merged**
