### PR TITLE
Convert reciprocal space and 3d grinder to OpenMP

### PR DESCRIPTION
**Pull request by stuwilkins**
This request converts the c routines to use OpenMP (as opposed to pthreads) and uses scatter gather for the grinder.

### CODE REVIEW

**Comment by stuwilkins** [comment]
Note : DO NOT MERGE YET! Submitting for discussion and comments.

**Comment by stuwilkins** [comment]
Attn @ericdill, This now uses OpenMP and is ready for trying on windows.

**Comment by ericdill** [comment]
Thanks for pinging me again. I saw this earlier and was waiting for it to pass tests. I suppose the most effective way for you to debug this on windows is going to be to get appveyor running CI for us on this project.  Do you have any idea what is required to get OpenMP going on Windows?

**Comment by licode** [comment]
I think openMP is included in most of the standard compilers (gcc/g++) in windows, so there is no more installation needed. http://openmp.org/wp/openmp-compilers/ 
However, it seems that openMP is not associated with standard gcc compiler in mac (installed with Xcode automatically). So I usually manually install another gcc using macport or brew in order to use openMP. 
This may cause some installation issue on mac?

**Comment by stuwilkins** [comment]
Thanks @licode this must be a cython problem as well when compiling extension modules no?

Should we put some compiler directives around the openmp lines so that we can compile without (and then use single core?)

**Comment by licode** [comment]
Yes, that will be helpful. cython works fine, although it may also include openMP in the backend.

**Comment by licode** [comment]
Just sent a PR to fix_ctrans. Please let me know how it goes.

**Comment by stuwilkins** [comment]
I think this is now ready for review and merging. Once that is done, I can work on the Windows bit, but this version is very light so might compile out of the box.

Attn @tacaswell @ericdill @licode.

**Comment by licode** [comment]
Thanks. I will take a look at this.

**Comment by licode** [comment]
Looks good to me.

**Pull request merged**
