### PR TITLE
Add 2D Savitzky–Golay filter

### PR DESCRIPTION
**Pull request by mpmdean**
This is to add a 2D Savitzky–Golay filter function in a new module skbeam/core/smoothing.py

@ericdill @danielballan 

#531

### CODE REVIEW

**Comment by mpmdean** [comment]
Hi @ericdill and @danielballan ,

Was this pull request ok?  Now that I read contributing.txt. It seems to imply I need to add a test and example?

**Comment by ericdill** [comment]
Hi @mpmdean sorry to not be responsive on this. I am in the middle of a move and so am occupied with unpacking 😢 .  yes you are correct, adding a test and an example makes your new code much more accessible to other folks wanting to use it.

**Comment by mpmdean** [comment]
No problem @ericdill 

Should the example be a notebook in this repository?
https://github.com/scikit-beam/scikit-beam-examples

Can you send me a link to get me started regarding how the tests are implemented?

**Comment by ericdill** [comment]
> Should the example be a notebook in this repository? https://github.com/scikit-beam/scikit-beam-examples

Yup

> Can you send me a link to get me started regarding how the tests are implemented?

I am not sure if we have a link on how to implement tests. Maybe @danielballan or @tacaswell have some ideas on how to get started there?

**Comment by mpmdean** [comment]
@ericdill @danielballan This pull request now has a test added. I'll probably have time to an example to

https://github.com/scikit-beam/scikit-beam-examples

In maybe 2-3 weeks time.

**Comment by danielballan** [comment]
The test looks good, and I see the docstring properly attributes the source of this example (the scipy cookbook) so I think this is good to merge.

**Comment by ericdill** [comment]
Thanks for the new feature @mpmdean . Looking forward to the example notebook whenever you have time 😄

**Pull request merged**
