### PR TITLE
MNT: Allow conda binaries for windows to be produced

### PR DESCRIPTION
**Pull request by ericdill**
~~Don't merge this until I know it is building windows skbeam properly~~ ready to go

[edit] updated on 2/22/16

### CODE REVIEW

**Comment by ericdill** [comment]
I *think* this is working now. I'm struggling with appveyor to get the windows builds going. After that is done, this will definitely be ready, until @stuwilkins does a major overhaul of the ctrans module and it compiles for windows!

**Comment by ericdill** [comment]
Ok, this allows windows conda binaries to at least be *built*, even though they are missing xray-fluorescence, so `xraylib` doesn't work, and the c extensions by @stuwilkins for rapid reciprocal space manipulations don't work either.  Any objections to merging this as-is, so I can can tag 0.0.8 and release binaries for all platforms?

**Comment by ericdill** [comment]
whoops... accidentally deleted this branch while cleaning up my branches :disappointed:

**Comment by sameera2004** [comment]
Looks good to me!

**Comment by ericdill** [comment]
For whatever reason github is not letting @sameera2004 merge this...  self-merging with approval from @sameera2004

**Pull request merged**
