### PR TITLE
Hist cp

### PR DESCRIPTION
**Pull request by tacaswell**
Replaces #449 

@chrisvam I have cherry-picked off the two commits related to the hist changes on to this branch. 

I suggest that if this is good to go we merge off of this, but if you want to add more commits I suggest force-pushing these commits to your branch.

### CODE REVIEW

**Comment by tacaswell** [comment]
@chrisvam Would you mind if I add some commits with exhastive tests on top of this?

**Comment by chrisvam** [comment]
Of course not.  That’s very kind of you.  Feel free to tell me what you would like and I can try to do it too.  I’m on vacation (traveling today) so in general my productivity will drop, but I will try to tidy up these issues with my PRs so we can get them out the door.

I haven’t fully understood yet, but it seems I didn’t use the right git procedure to submit the PRs (you had to cherry-pick some stuff?).  I had one fork, and two branches in it, one for each PR.  Maybe when we talk next I can learn what I should do differently (or you can explain via email if it’s easy).

chris

On Jul 21, 2016, at 6:15 AM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:


@chrisvam<https://github.com/chrisvam> Would you mind if I add some commits with exhastive tests on top of this?

**Comment by tacaswell** [comment]
You had 3 open PRs, one from your 'master', and then two other branches.  The 'master' on your fork had commits that were unrelated to the PR at hand and not on the upstream master (which is why #449 has 44 commits where as this PR as 2).  I cherry-picked the relevant commits off of your branch and on top of the current upstream master.  This eliminates the need for the commits where you delete the unrelated code.

I also eliminated (on all three of the re-opened PRs) the merges from master back into the feature branch.

**Comment by chrisvam** [comment]
On Jul 21, 2016, at 10:34 AM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:


You had 3 open PRs, one from your 'master', and then two other branches. The 'master' on your fork had commits that were unrelated to the PR at hand and not on the upstream master (which is why #449<https://github.com/scikit-beam/scikit-beam/pull/449> has 44 commits where as this PR as 2). I cherry-picked the relevant commits off of your branch and on top of the current upstream master. This eliminates the need for the commits where you delete the unrelated code.


So I learn:  in future is it cleaner if I have one PR per fork?  I tried to do one PR per branch this time, but evidently that still created some headache for you.  Perhaps I should not issue PR’s from branches, first merging back into my master and then submitting the PR from there?  But then it’s not clear to me how to have multiple PR’s in progress.  Thanks for any advice…

chris

**Comment by CJ-Wright** [comment]
Personally I like to make a separate branch for each feature/PR after updating my master to match the main master. This way you have no extra commits on any of your PRs. This way you also avoid master to master merges, which are a little less elegant in the history.

**Comment by tacaswell** [comment]
as @CJ-Wright says, one PR per branch (and many branches per fork), just make sure that the root of the feature branch is the upstream branch you are targeting with the PR.

**Comment by tacaswell** [comment]
My plans for more tests are dependent on using pytest (which we are not yet).

Merging as-is.

**Comment by tacaswell** [comment]
:sheep: hit the wrong UI button, waiting for travis again

**Pull request merged**
