### PR TITLE
CI: Build docs separately from automated testing.

### PR DESCRIPTION
**Pull request by ericdill**
This is something that was requested by @tacaswell because the sphinx
logs spit out a tremendous amount of information that makes it difficult
to examine the logs for test failures.

### CODE REVIEW

**Comment by ericdill** [comment]
Note that this should be merged after #414

**Comment by ericdill** [comment]
ping @tacaswell . As requested, docs are building separately.

**Comment by tacaswell** [comment]
:+1: Awesome! thanks!

**Comment by ericdill** [comment]
Welcome.  It was a good idea! Thanks for the green button click

**Pull request merged**
