### PR TITLE
fixed std bug

### PR DESCRIPTION
**Pull request by ordirules**
fixes issue with `std_` reference
@danielballan

### CODE REVIEW

**Comment by ordirules** [comment]
Do you know what's wrong with this Travis fail?
```
    Traceback (most recent call last):

      File "/home/travis/mc/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 138, in _new_conn

        (self.host, self.port), self.timeout, **extra_kw)

      File "/home/travis/mc/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection

        raise err

      File "/home/travis/mc/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection

        sock.connect(sa)

    socket.timeout: timed out
```

**Comment by ericdill** [comment]
It's an issue with anaconda.org. Restarting the build on Travis usually fixes problems like this. I'll do that now

**Comment by ordirules** [comment]
I had restarted once in the past and it didn't work, so I wasn't sure.

looks like it works now, thanks :-)

**Comment by ordirules** [comment]
just to be sure, @ericdill just two of us needed to merge? confirm and I'll merge.
I did this once, but just want to be careful...
@danielballan may want to give input before hand as well, I'd be tempted to wait for him after this weekend

**Comment by ericdill** [comment]
These changes seem sensible to me but I am not as familiar with this portion of the codebase, so :+1: on wanting input from @danielballan here

**Comment by danielballan** [comment]
Sorry for the hold-up, guys. I took vacation days on Thurs/Friday that were going to expire if I didn't use them.

**Comment by ericdill** [comment]
Vacations are good! Never have to apologize for taking time off :grin:

**Comment by ordirules** [comment]
ditto :-)

I figured we should wait because you always catch the very subtle overlooked details ;-)

**Comment by ordirules** [comment]
Glad this works properly finally :-).

For the record, commits 05fea0380870ea3c7a7bf71a6deb4b640dfe6917 (PR #482 ) up to this one b7e2b94c54acb475accee03c2188ec5390f8ea25 have a buggy version of rbinstat. None of these versions should be implemented.

**Pull request merged**
