### PR TITLE
ENH: Updates to allow sequential processing

### PR DESCRIPTION
**Pull request by stuwilkins**
This is currently a WIP but this is an effort to allow partial and sequential clunking of the data. Please do not merge yet

### CODE REVIEW

**Comment by danielballan** [comment]
@stuwilkins It sounds like this could be more valuable now that we have SWMR. Have you had a chance to revisit it?

**Comment by tacaswell** [comment]
@licode can you review this?

**Comment by licode** [comment]
Sure, I will take care of this.

**Comment by licode** [comment]
Though I am a big fan of cython these days.

**Comment by licode** [comment]
I think there might be better way to release and obtain GIL. 

This PR looks good to me in overall.

**Pull request merged**
