### PR TITLE
DOC: Include API docs for more of the modules

### PR DESCRIPTION
**Pull request by danielballan**
In the process of reading through the codebase to remind myself what's in it, I wrote a one-sentence summary of each module and added it in the index. It's not polished, but neither are some of our modules.

### CODE REVIEW

**Comment by danielballan** [comment]
2/6 of the Travis builds failed on a transient network error, but the others passed. Can this be merged?

**Comment by danielballan** [comment]
Bump. I went looking for this content today in the docs. Would be useful to have in merged.

**Comment by sameera2004** [comment]
@danielballan I think it is useful, I will add more detail descriptions to correlation, roi and and speckle modules

**Comment by ericdill** [comment]
fine by me. Can always update as needed right?

**Pull request merged**
